classdef animalList
    
    properties
        % edit here for a list of experimental animals that will populate
        % the menu on the GUI
        mouseList = {'none'; ...
                     'f26';  ...
                     'f27';  ...
                     'f29';  ...
                     'f32';  ...
                     'test';  ...
                     };
        
    end
    
    % these are experimental parameters, each mouse in the list above shold
    % have 
    properties (Constant)
        
        templateDir = {'none';...
            'C:\Users\MMM_3p1_SI\Documents\wftoolbox\templates\f26Template';...
            'C:\Users\MMM_3p1_SI\Documents\wftoolbox\templates\f27Template';...
            'C:\Users\MMM_3p1_SI\Documents\wftoolbox\templates\f29Template';...
            'C:\Users\MMM_3p1_SI\Documents\wftoolbox\templates\f32Template';...
            };
        
        % inactivation grids to be loaded in association with each mouse
        gridList  = {'none';...
                     'fullGridBilateral.mat';               ...
                     'fullGridBilateral.mat';               ...
                     'fullGridBilateral.mat';               ...
                     'fullGridBilateral.mat';               ...
                     'fullGrid.mat';               ...
                     };
        
        % laser power           
        powerList = {nan;...
                     1.5; ...
                     1.5; ...
                     1.5; ...
                     1.5; ...
                     1.5; ...
                     };
        
        % special case to run different powers within a session          
        varPower  = [nan;  ...
                     false;     ...
                     false;     ...
                     false;     ...
                     false;     ...
                     false;     ...
                     ];
        
        % trial epoch in which to turn the laser on           
        epochList = {'none';...
                     'whole';   ...
                     'cue';     ...
                     'whole';   ...
                     'whole';   ...
                     'whole';   ...
                     };
        
        % whether to actually run the laser experiments or not. this is intended
        % as an experiment scheduling aid, will not automatically  override any laser
        % functions 
        runOnLsr  = [nan;...
                     true;     ...
                     true;     ...
                     false;    ...
                     false;    ...
                     false;    ...
                     ];

    end
    
    methods
        
        function obj = addToList(obj,mouse)
            obj.mouseList{end+1} = mouse{1};
            obj.mouseList{end+1} = 'add new';
        end
    end
end